version: '3'
services:
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: sail
      PMA_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - sail
networks:
  sail:
    driver: bridge